apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: go-example
  namespace: argocd
  annotation:
    argocd-image-updater.argoproj.io/image-list: test=registry-1.docker.io/anieo/go-example
    argocd-image-updater.argoproj.io/test.allow-tags: 'regexp:^v[0-9]+.[0-9]+-[0-9]+-[0-9a-zA-Z]$'
    argocd-image-updater.argoproj.io/test.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: chart/go-example
    helm:
      releaseName: go-example
    repoURL: 'https://github.com/anie/go-example.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: null
