apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: go-example
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: test=anieo/go-example
    argocd-image-updater.argoproj.io/test.allow-tags: 'regexp:^v[0-9]+.[0-9]+-[0-9]+-[0-9a-zA-Z]+$'
    argocd-image-updater.argoproj.io/test.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git

    argocd-image-updater.argoproj.io/test.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/test.helm.image-tag: image.tag
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: chart/go-example
    helm:
      releaseName: go-example
    repoURL: 'https://github.com/anieo/go-example.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: null
